export const API_BASE_URL = "http://localhost:3000/api";

export const LOCAL_KEY_FROM_USER = "LOCAL_KEY_FROM_USER";
export const LOCAL_KEY_IS_AUTHENTICATED = "LOCAL_KEY_IS_AUTHENTICATED";
export const LOCAL_KEY_POST_EDIT_STATE = "LOCAL_KEY_POST_EDIT_STATE";
